title: 读要speak-LO
description: Read and speak LOUD to OUTPUT.
author: My Name
email: my@email.com
lang: en-us
copyright: '&#x2117; &amp; &#xA9; 2020'
logo: /assets/img/logo.png
exclude:
  - Gemfile
  - Gemfile.lock
url: https://fuyininfo.github.io/podcast-pages
