title: 读要speak-LO
description: Read and speak to LOUD OUTPUT.
author: RSLO
email: fuyininfo@disroot.org
lang: en-us
copyright: '&#x2117; &amp; &#xA9; 2020'
logo: /assets/img/logo.png
exclude:
  - Gemfile
  - Gemfile.lock
url: https://fuyininfo.github.io
baseurl: "/podcast-pages"
future: true
